{
 "title": "Barman",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(barman_up, instance)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(barman_up, server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Barman instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance.*\",mountpoint=\"/var/lib/barman\"} - node_filesystem_avail_bytes{instance=~\"$instance.*\",mountpoint=\"/var/lib/barman\"}) / node_filesystem_size_bytes{instance=~\"$instance.*\",mountpoint=~\"/var/lib/barman\"} * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Backup partition (/var/lib/barman)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance.*\",mountpoint=\"/var/lib/barman\"} - node_filesystem_avail_bytes{instance=~\"$instance.*\",mountpoint=\"/var/lib/barman\"}",
     "legendFormat": "$instance: used disk space"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance.*\",mountpoint=\"/var/lib/barman\"}",
     "legendFormat": "$instance: available disk space"
    }
   ]
  },
  {
   "title": "Barman errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(barman_up{instance=~\"$instance.*\"}) - sum(barman_up{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Number of servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(barman_backups_total{instance=~\"$instance.*\"}) by (server)"
    }
   ]
  },
  {
   "title": "Total number of backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(barman_backups_total{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Server $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "server",
   "targets": [
    {}
   ]
  },
  {
   "title": "Last backup age",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hour(time()- barman_last_backup{instance=~\"$instance.*\", server=\"$server\"})",
     "legendFormat": "$instance: {{ server }}"
    }
   ]
  },
  {
   "title": "First backup age",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - barman_first_backup{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "barman_backups_failed{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - barman_last_backup{instance=~\"$instance.*\", server=\"$server\"}",
     "legendFormat": "$instance: {{ server }}"
    }
   ]
  },
  {
   "title": "Last backup copy time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "barman_last_backup_copy_time{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Available backups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "barman_backups_total{instance=~\"$instance.*\", server=\"$server\"} - barman_backups_failed{instance=~\"$instance.*\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Last backup size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "barman_backup_size{instance=~\"$instance.*\", server=\"$server\", number=\"1\"}",
     "legendFormat": "$instance: {{ server }} backup size"
    },
    {
     "expr": "barman_backup_wal_size{instance=~\"$instance.*\", server=\"$server\", number=\"1\"}",
     "legendFormat": "$instance: {{ server }} WAL size"
    }
   ]
  }
 ]
}